### ISSUE TITLE
Redis cache

### ISSUE THREAD

**Issue by aldotestino** [aldotestino/custom-login#1]
Usare Redis per effettuare il caching degli utenti loggati, nel middleware `authenticateUser`

```yml
redis:
  image: redis
  container_name: redis
  expose:
    - 6379
```
